### PR TITLE
A better attempt at styles

### PR DESCRIPTION
**Pull request by tildeee**
@Hamled Do with this what you'd like! Take it or don't, that's fine with me.

Note: I obviously hardcoded a certain height for some of these views. You'll see!

screen shot 2017-12-09 at 1 29 30 am

### CODE REVIEW

**Comment by tildeee** [comment]
screen shot 2017-12-09 at 4 31 12 pm

**Comment by Hamled** [comment]
Looks like a good layout setup. I'll use this as the basis for defining the various list element styles and content, then turn them into Underscore template scripts.

**Comment by Hamled** [comment]
Oh I didn't see the most recent updates. Excellent!

**Review by Hamled — APPROVED** [review]
Not sure if you're still working on this, but whenever you feel it's in a good spot go ahead and merge it in.

**Comment by Hamled** [comment]
Merging this in since I have the baseline done and it is based on this branch.

**Pull request merged**
